version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: arm64v8/wordpress:apache
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-theme:/var/www/html/wp-content/themes/
    ports:
      - "3100:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  setup:
    depends_on:
      - wordpress
    image: semantic_setup
    build:
      context: .
      dockerfile: ./etc/docker/wordpress/Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    command: /start
volumes:
  db_data: {}
  wordpress_data: {}
