version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: arm64v8/wordpress:apache
    volumes:
      - wordpress_data:/var/www/html
      - ./clients-theme:/var/www/html/wp-content/themes/
      - ./clients-plugins/wp-theme-almex:/var/www/html/wp-content/plugins/
    ports:
      - "3100:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  setup:
    depends_on:
      - wordpress
    image: semantic_setup
    build:
      context: .
      dockerfile: ./etc/docker/wordpress/Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    command: /start
  composer:
    depends_on:
      - wordpress
    restart: 'no'
    container_name: composer
    image: composer:1.10.12
    working_dir: /var/www/html
    command: composer update -d /var/www/html/wp-content/themes/almex-theme
    volumes:
      - ./clients-theme:/var/www/html/wp-content/themes/
volumes:
  db_data: {}
  wordpress_data: {}
